name: Update RetroArch on itch.io

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

env:
  ITCH_USERNAME: retroarchofficial
  ITCH_PROJECT: retroarch
  STABLE_VERSION: 1.19.1

jobs:
  update-retroarch-nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux]
        arch: [x86, x86_64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Butler
      uses: fpscan/setup-butler@7f0179e16a803bb780c3cee42a85ef35abc501f6

    - name: Set nightly build date
      run: echo "NIGHTLY_DATE=$(date +'%d.%m.%Y')" >> $GITHUB_ENV

    - name: Download RetroArch
      run: |
        URL="https://buildbot.libretro.com/nightly/${{ matrix.os }}/${{ matrix.arch }}/RetroArch.7z"
        echo "Downloading from: $URL"
        wget $URL
        7z x RetroArch.7z

    - name: Prepare package for itch.io
      run: |
        if [ "${{ matrix.os }}" == "windows" ]; then
          mv RetroArch-Win${{ matrix.arch == 'x86_64' && '64' || '32' }} RetroArch
        else
          mv RetroArch-Linux-${{ matrix.arch }} RetroArch
        fi

    - name: Push to itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: |
        butler push RetroArch ${{ env.ITCH_USERNAME }}/${{ env.ITCH_PROJECT }}:${{ matrix.os }}-${{ matrix.arch }}-nightly --userversion ${{ env.NIGHTLY_DATE }}

  update-retroarch-stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux]
        arch: [x86, x86_64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Butler
      uses: jdno/setup-butler@v1

    - name: Download RetroArch
      run: |
        URL="https://buildbot.libretro.com/stable/${{ env.STABLE_VERSION }}/${{ matrix.os }}/${{ matrix.arch }}/RetroArch.7z"
        echo "Downloading from: $URL"
        wget $URL
        7z x RetroArch.7z

    - name: Prepare package for itch.io
      run: |
        if [ "${{ matrix.os }}" == "windows" ]; then
          mv RetroArch-Win${{ matrix.arch == 'x86_64' && '64' || '32' }} RetroArch
        else
          mv RetroArch-Linux-${{ matrix.arch }} RetroArch
        fi

    - name: Push to itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: |
        butler push RetroArch ${{ env.ITCH_USERNAME }}/${{ env.ITCH_PROJECT }}:${{ matrix.os }}-${{ matrix.arch }}-stable --userversion ${{ env.STABLE_VERSION }}
      if: github.event_name == 'workflow_dispatch'
